# Generated by Django 5.2.6 on 2025-09-29 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='desc',
            new_name='desc_data',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='title',
            new_name='title_data',
        ),
    ]
