# Generated by Django 5.2.6 on 2025-10-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_historymodel_delete_deletedtaskmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historymodel',
            name='deleted_at',
        ),
    ]
