# Generated by Django 5.2.6 on 2025-10-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_taskmodel_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='original_id',
            field=models.IntegerField(default=0),
        ),
    ]
